INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (34,2,N'www.enter.ru',N'Autos and Vehicles');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (35,2,N'www.enter.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (36,2,N'www.enter.ru',N'Shopping > Home and Garden');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (37,2,N'www.enter.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (38,3,N'wikimart.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (39,3,N'wikimart.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (40,3,N'wikimart.ru',N'Shopping > General Merchandise');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (41,3,N'wikimart.ru',N'People and Society');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (42,4,N'www.ozon.ru',N'Books and Literature');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (43,4,N'www.ozon.ru',N'Books and Literature > Book Retailers');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (44,4,N'www.ozon.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (45,4,N'www.ozon.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (46,5,N'www.letu.ru',N'Beauty and Fitness > Cosmetics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (47,5,N'www.letu.ru',N'Health > Products and Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (48,5,N'www.letu.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (49,5,N'www.letu.ru',N'Arts and Entertainment > Music and Audio');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (50,5,N'www.letu.ru',N'Shopping > Jewelry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (51,6,N'www.quelle.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (52,6,N'www.quelle.ru',N'Shopping > Clothing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (53,6,N'www.quelle.ru',N'Games > Video Games');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (54,6,N'www.quelle.ru',N'Internet and Telecom > Search Engine');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (55,7,N'www.tehnosila.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (56,7,N'www.tehnosila.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (57,7,N'www.tehnosila.ru',N'Shopping > Home and Garden');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (58,7,N'www.tehnosila.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (59,8,N'www.mvideo.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (60,8,N'www.mvideo.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (61,8,N'www.mvideo.ru',N'Shopping > General Merchandise');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (62,8,N'www.mvideo.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (63,9,N'www.asos.com',N'Shopping > Clothing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (64,9,N'www.asos.com',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (65,9,N'www.asos.com',N'Shopping > Coupons');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (66,10,N'moscow.shop.megafon.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (67,10,N'moscow.shop.megafon.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (68,10,N'moscow.shop.megafon.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (69,10,N'moscow.shop.megafon.ru',N'Business and Industry > Real Estate');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (70,11,N'www.bgshop.ru',N'Business and Industry > Publishing and Printing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (71,11,N'www.bgshop.ru',N'Food and Drink');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (72,11,N'www.bgshop.ru',N'People and Society > Religion and Spirituality');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (73,11,N'www.bgshop.ru',N'Arts and Entertainment');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (74,12,N'www.shop.mts.ru',N'Games > Video Games');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (75,12,N'www.shop.mts.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (76,12,N'www.shop.mts.ru',N'Shopping > Sports');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (77,12,N'www.shop.mts.ru',N'News and Media');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (78,13,N'nikonstore.ru',N'Internet and Telecom');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (79,13,N'nikonstore.ru',N'Business and Industry > Construction and Maintenance');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (80,13,N'nikonstore.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (81,13,N'nikonstore.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (82,14,N'vans.ru',N'Arts and Entertainment > Music and Audio');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (83,14,N'vans.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (84,14,N'vans.ru',N'Shopping > Clothing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (85,14,N'vans.ru',N'Travel > Tourism');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (86,15,N'www.eldorado.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (87,15,N'www.eldorado.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (88,15,N'www.eldorado.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (89,15,N'www.eldorado.ru',N'Computer and Electronics > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (90,16,N'www.komus.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (91,16,N'www.komus.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (92,16,N'www.komus.ru',N'Business and Industry > Marketing and Advertising');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (93,17,N'www.bonprix.ru',N'Shopping > Clothing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (94,17,N'www.bonprix.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (95,17,N'www.bonprix.ru',N'Internet and Telecom > Search Engine');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (96,17,N'www.bonprix.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (97,18,N'www.dns-shop.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (98,18,N'www.dns-shop.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (99,18,N'www.dns-shop.ru',N'Shopping > General Merchandise');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (100,18,N'www.dns-shop.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (101,18,N'www.dns-shop.ru',N'Games > Video Games');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (102,19,N'shop.huawei.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (103,19,N'shop.huawei.ru',N'News and Media > Technology News');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (104,19,N'shop.huawei.ru',N'Computer and Electronics > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (105,19,N'shop.huawei.ru',N'Shopping > Consumer Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (106,20,N'www.wildberries.ru',N'Shopping > Clothing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (107,20,N'www.wildberries.ru',N'Internet and Telecom > Search Engine');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (108,20,N'www.wildberries.ru',N'Business and Industry > Marketing and Advertising');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (109,20,N'www.wildberries.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (110,21,N'www.labirint.ru',N'Books and Literature');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (111,21,N'www.labirint.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (112,21,N'www.labirint.ru',N'Home and Garden > Nursery and Playroom');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (113,21,N'www.labirint.ru',N'Shopping > General Merchandise');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (114,21,N'www.labirint.ru',N'Books and Literature > Book Retailers');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (115,22,N'www.befree.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (116,22,N'www.befree.ru',N'Shopping > Clothing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (117,22,N'www.befree.ru',N'Arts and Entertainment');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (118,22,N'www.befree.ru',N'People and Society');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (119,23,N'shop.lenovo.ru',N'Business and Industry > Marketing and Advertising');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (120,23,N'shop.lenovo.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (121,23,N'shop.lenovo.ru',N'News and Media');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (122,23,N'shop.lenovo.ru',N'Computer and Electronics');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (123,24,N'www.lamoda.ru',N'Shopping > Clothing');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (124,24,N'www.lamoda.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (125,24,N'www.lamoda.ru',N'Shopping > Sports');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (126,24,N'www.lamoda.ru',N'Internet and Telecom > Ad Network');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (127,25,N'www.1c-bitrix.ru',N'Internet and Telecom');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (128,25,N'www.1c-bitrix.ru',N'Business and Industry');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (129,25,N'www.1c-bitrix.ru',N'Computer and Electronics > Software');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (130,25,N'www.1c-bitrix.ru',N'Shopping > Children');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (131,26,N'moskva.beeline.ru',N'Internet and Telecom > Telecommunications');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (132,26,N'moskva.beeline.ru',N'Shopping');
INSERT `AudienceInterestsCategories` (`ID`,`SiteID`,`Link`,`Category`) VALUES (133,26,N'moskva.beeline.ru',N'Sports');
