INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (246,2,N'www.enter.ru',N'feedback@enter.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (247,2,N'www.enter.ru',N'purchase@enter.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (248,2,N'www.enter.ru',N'arenda@enter.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (249,2,N'www.enter.ru',N'reklama@enter.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (250,2,N'www.enter.ru',N'podbor@enter.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (252,2,N'www.enter.ru',N'+7 (495) 775-00-06',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (253,2,N'www.enter.ru',N'+7 495 775 91 75',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (254,2,N'www.enter.ru',N'8 800 700 00 09',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (255,3,N'wikimart.ru',N'info@wikimart.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (256,3,N'wikimart.ru',N'8-800-333-92-16',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (257,10,N'moscow.shop.megafon.ru',N'8 (800) 550 5858',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (258,6,N'www.quelle.ru',N'welcome@quelle.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (260,4,N'www.ozon.ru',N'8 800 234-60-06',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (263,5,N'www.letu.ru',N'8-800-200-23-45',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (264,7,N'www.tehnosila.ru',N'8 495 775 21 00',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (265,7,N'www.tehnosila.ru',N'8 800 775 21 00',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (266,8,N'www.mvideo.ru',N'24@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (267,8,N'www.mvideo.ru',N'job@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (268,8,N'www.mvideo.ru',N'uliya.Zotova@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (269,8,N'www.mvideo.ru',N'lga.Kobzareva@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (270,8,N'www.mvideo.ru',N'corporate@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (271,8,N'www.mvideo.ru',N'zakupki@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (272,8,N'www.mvideo.ru',N'adv@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (273,8,N'www.mvideo.ru',N'expansion@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (274,8,N'www.mvideo.ru',N'italiy.Markunskiy@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (275,8,N'www.mvideo.ru',N'olga.bayutina@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (276,8,N'www.mvideo.ru',N'ir@mvideo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (277,8,N'www.mvideo.ru',N'8-800-200-23-11',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (278,8,N'www.mvideo.ru',N'8 495 644-28-48',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (279,8,N'www.mvideo.ru',N'+7 (495) 644-28-48',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (282,12,N'www.shop.mts.ru',N'mail@shop.mts.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (283,12,N'www.shop.mts.ru',N'8 (800) 250 05 05',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (284,11,N'www.bgshop.ru',N'web.logist@bgshop.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (285,11,N'www.bgshop.ru',N'+7 (495) 781-19-12',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (286,11,N'www.bgshop.ru',N'+7 (495) 781-19-00',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (288,15,N'www.eldorado.ru',N'8 800 555-11-11',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (289,15,N'www.eldorado.ru',N'8 800 555 11 11',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (290,22,N'www.befree.ru',N'8-800-250-01-02',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (293,19,N'shop.huawei.ru',N'support@huawei.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (294,19,N'shop.huawei.ru',N'mobile.ru@huawei.com',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (295,19,N'shop.huawei.ru',N'suppo22222@webim.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (297,19,N'shop.huawei.ru',N'8 800 7001677',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (298,19,N'shop.huawei.ru',N'8 800 7001606',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (299,19,N'shop.huawei.ru',N'+7 812 3855337',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (300,18,N'www.dns-shop.ru',N'8-499-704-46-40',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (301,21,N'www.labirint.ru',N'+7 495 745-95-25',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (302,17,N'www.bonprix.ru',N'info@bonprix.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (303,17,N'www.bonprix.ru',N'info@bonprix.com',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (304,19,N'shop.huawei.ru',N'8 (800) 7001606',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (305,23,N'shop.lenovo.ru',N'8-800-301-74-07',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (306,23,N'shop.lenovo.ru',N'8-800-301-7407',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (308,33,N'www.detmir.ru',N'8 (800) 250-00-00',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (309,24,N'www.lamoda.ru',N'claims@lamoda.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (310,24,N'www.lamoda.ru',N'help@lamoda.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (311,24,N'www.lamoda.ru',N'8 800 333-23-59',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (312,24,N'www.lamoda.ru',N'+7 (499) 750-14-50',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (313,24,N'www.lamoda.ru',N'+7 (812) 389-20-10',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (314,24,N'www.lamoda.ru',N'+7 (343) 226-06-10',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (315,24,N'www.lamoda.ru',N'+7 (831) 261-30-11',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (316,24,N'www.lamoda.ru',N'+7 (383) 207-98-97',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (317,24,N'www.lamoda.ru',N'+7 (863) 209-89-21',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (318,24,N'www.lamoda.ru',N'+7 (846) 229-55-15',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (319,27,N'ru.wix.com',N'wixofday@wix.com',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (320,25,N'www.1c-bitrix.ru',N'info@1c-bitrix.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (321,25,N'www.1c-bitrix.ru',N'sales@1c-bitrix.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (322,25,N'www.1c-bitrix.ru',N'marketing@1c-bitrix.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (323,25,N'www.1c-bitrix.ru',N'partners@1c-bitrix.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (324,25,N'www.1c-bitrix.ru',N'ukraine@1c-bitrix.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (325,25,N'www.1c-bitrix.ru',N'8-800-250-1860',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (326,25,N'www.1c-bitrix.ru',N'8-800-250-18-60',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (327,25,N'www.1c-bitrix.ru',N'+7 (495) 229-14-41',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (328,28,N'www.dochkisinochki.ru',N'8 495 660-72-01',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (329,28,N'www.dochkisinochki.ru',N'+7 (495) 660-72-01',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (330,31,N'www.svyaznoy.ru',N'8 (800) 700 43 43',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (331,31,N'www.svyaznoy.ru',N'8 (800) 700 50 00',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (332,31,N'www.svyaznoy.ru',N'8 (800) 700 99 22',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (333,29,N'www.phpshop.ru',N'8-800-700-11-15',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (334,29,N'www.phpshop.ru',N'+7 (495) 989-11-15',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (335,29,N'www.phpshop.ru',N'+7-495-989-11-15',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (336,121,N'www.toy.ru',N'info@toy.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (337,121,N'www.toy.ru',N'8(495) 215-22-44',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (338,121,N'www.toy.ru',N'8 (800) 500-23-70',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (339,121,N'www.toy.ru',N'8(800) 500-23-70',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (340,106,N'www.220-volt.ru',N'+7 (495) 745-50-55',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (341,56,N'www.chitai-gorod.ru',N'8354-8962605',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (342,75,N'open-style.ru',N'office@open-style.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (343,75,N'open-style.ru',N'radchenko_olesyav@mail.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (344,75,N'open-style.ru',N'8-913-066-8245',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (345,75,N'open-style.ru',N'8-929-327-39-01',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (346,75,N'open-style.ru',N'8-913-066-82-45',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (347,113,N'www.fabricasaitov.ru',N'8 (800) 333 45 11',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (348,74,N'www.insales.ru',N'sales@insales.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (349,74,N'www.insales.ru',N'support@insales.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (350,74,N'www.insales.ru',N'+7 (495) 649 83 14',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (351,74,N'www.insales.ru',N'8 800 555 10 61',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (352,98,N'ru.jimdo.com',N'support@jimdo.com',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (353,98,N'ru.jimdo.com',N'press@jimdo.ru',N'email');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (354,98,N'ru.jimdo.com',N'8-800-100-9693',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (356,104,N'baon.ru',N'+7 (495) 150-11-05',N'phone');
INSERT `Contacts` (`ID`,`SiteID`,`LInk`,`Contact`,`Type`) VALUES (357,104,N'baon.ru',N'+7 (495) 637-87-07',N'phone');
