INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (41,2,N'www.enter.ru',N'Russia',94.56);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (42,2,N'www.enter.ru',N'Ukraine',1.67);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (43,2,N'www.enter.ru',N'United States',0.53);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (44,2,N'www.enter.ru',N'Belarus',0.52);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (45,2,N'www.enter.ru',N'Turkey',0.42);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (46,3,N'wikimart.ru',N'Russia',91.71);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (47,3,N'wikimart.ru',N'Ukraine',3.37);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (48,3,N'wikimart.ru',N'Belarus',0.99);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (49,3,N'wikimart.ru',N'Kazakhstan',0.54);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (50,3,N'wikimart.ru',N'United States',0.48);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (51,4,N'www.ozon.ru',N'Russia',88.71);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (52,4,N'www.ozon.ru',N'Ukraine',4.5);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (53,4,N'www.ozon.ru',N'Belarus',1.16);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (54,4,N'www.ozon.ru',N'Kazakhstan',0.85);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (55,4,N'www.ozon.ru',N'United States',0.56);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (56,5,N'www.letu.ru',N'Russia',93.75);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (57,5,N'www.letu.ru',N'Ukraine',1.99);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (58,5,N'www.letu.ru',N'Belarus',0.56);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (59,5,N'www.letu.ru',N'Vietnam',0.43);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (60,5,N'www.letu.ru',N'United States',0.35);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (61,6,N'www.quelle.ru',N'Russia',95.06);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (62,6,N'www.quelle.ru',N'Ukraine',2.36);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (63,6,N'www.quelle.ru',N'Turkey',0.31);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (64,6,N'www.quelle.ru',N'United States',0.28);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (65,6,N'www.quelle.ru',N'Kazakhstan',0.27);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (66,7,N'www.tehnosila.ru',N'Russia',95.47);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (67,7,N'www.tehnosila.ru',N'Ukraine',1.16);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (68,7,N'www.tehnosila.ru',N'Belarus',0.8);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (69,7,N'www.tehnosila.ru',N'Turkey',0.34);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (70,7,N'www.tehnosila.ru',N'United States',0.33);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (71,8,N'www.mvideo.ru',N'Russia',95.21);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (72,8,N'www.mvideo.ru',N'Ukraine',1.15);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (73,8,N'www.mvideo.ru',N'Belarus',0.52);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (74,8,N'www.mvideo.ru',N'United States',0.49);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (75,8,N'www.mvideo.ru',N'Turkey',0.3);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (76,9,N'www.asos.com',N'United Kingdom',26.99);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (77,9,N'www.asos.com',N'United States',17.68);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (78,9,N'www.asos.com',N'Australia',6.12);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (79,9,N'www.asos.com',N'Russia',4.83);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (80,9,N'www.asos.com',N'Spain',3.97);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (81,10,N'moscow.shop.megafon.ru',N'Russia',92.42);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (82,10,N'moscow.shop.megafon.ru',N'Ukraine',2.67);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (83,10,N'moscow.shop.megafon.ru',N'Belarus',0.54);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (84,10,N'moscow.shop.megafon.ru',N'Turkey',0.51);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (85,10,N'moscow.shop.megafon.ru',N'Armenia',0.42);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (86,11,N'www.bgshop.ru',N'Russia',90.07);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (87,11,N'www.bgshop.ru',N'Ukraine',2.24);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (88,11,N'www.bgshop.ru',N'Kazakhstan',1.48);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (89,11,N'www.bgshop.ru',N'Latvia',1.42);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (90,11,N'www.bgshop.ru',N'Belarus',0.57);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (91,12,N'www.shop.mts.ru',N'Russia',95.2);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (92,12,N'www.shop.mts.ru',N'Ukraine',1.37);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (93,12,N'www.shop.mts.ru',N'Belarus',0.44);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (94,12,N'www.shop.mts.ru',N'United States',0.44);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (95,12,N'www.shop.mts.ru',N'Turkey',0.29);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (96,13,N'nikonstore.ru',N'Russia',90.96);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (97,13,N'nikonstore.ru',N'Ukraine',2.88);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (98,13,N'nikonstore.ru',N'Belarus',1.98);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (99,13,N'nikonstore.ru',N'United States',0.81);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (100,13,N'nikonstore.ru',N'Turkey',0.73);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (101,14,N'vans.ru',N'Russia',90.06);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (102,14,N'vans.ru',N'United Kingdom',3.14);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (103,14,N'vans.ru',N'Ukraine',2.99);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (104,14,N'vans.ru',N'United States',0.92);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (105,14,N'vans.ru',N'Belarus',0.65);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (106,15,N'www.eldorado.ru',N'Russia',93.87);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (107,15,N'www.eldorado.ru',N'Ukraine',2.26);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (108,15,N'www.eldorado.ru',N'Belarus',0.73);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (109,15,N'www.eldorado.ru',N'Turkey',0.38);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (110,15,N'www.eldorado.ru',N'United States',0.36);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (111,16,N'www.komus.ru',N'Russia',94.46);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (112,16,N'www.komus.ru',N'Ukraine',1.74);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (113,16,N'www.komus.ru',N'Turkey',0.43);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (114,16,N'www.komus.ru',N'Kazakhstan',0.38);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (115,16,N'www.komus.ru',N'United States',0.37);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (116,17,N'www.bonprix.ru',N'Russia',94.49);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (117,17,N'www.bonprix.ru',N'Ukraine',3.39);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (118,17,N'www.bonprix.ru',N'Kazakhstan',0.48);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (119,17,N'www.bonprix.ru',N'United States',0.2);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (120,17,N'www.bonprix.ru',N'Turkey',0.17);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (121,18,N'www.dns-shop.ru',N'Russia',91.88);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (122,18,N'www.dns-shop.ru',N'Ukraine',3.71);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (123,18,N'www.dns-shop.ru',N'Belarus',0.52);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (124,18,N'www.dns-shop.ru',N'United States',0.51);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (125,18,N'www.dns-shop.ru',N'Kazakhstan',0.47);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (126,19,N'shop.huawei.ru',N'Russia',89.61);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (127,19,N'shop.huawei.ru',N'Ukraine',3.21);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (128,19,N'shop.huawei.ru',N'Belarus',1.19);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (129,19,N'shop.huawei.ru',N'China',0.76);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (130,19,N'shop.huawei.ru',N'United States',0.71);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (131,20,N'www.wildberries.ru',N'Russia',95.01);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (132,20,N'www.wildberries.ru',N'Ukraine',2.08);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (133,20,N'www.wildberries.ru',N'Belarus',0.59);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (134,20,N'www.wildberries.ru',N'Kazakhstan',0.3);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (135,20,N'www.wildberries.ru',N'United States',0.29);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (136,21,N'www.labirint.ru',N'Russia',83.91);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (137,21,N'www.labirint.ru',N'Ukraine',6.21);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (138,21,N'www.labirint.ru',N'Belarus',2.08);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (139,21,N'www.labirint.ru',N'Kazakhstan',1.26);
INSERT `CountriesTraffic` (`ID`,`SiteID`,`Link`,`Country`,`Share`) VALUES (140,21,N'www.labirint.ru',N'United States',0.66);
