INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (71,2,N'www.enter.ru',N'энтер',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (72,2,N'www.enter.ru',N'enter',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (73,2,N'www.enter.ru',N'ентер',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (74,2,N'www.enter.ru',N'enter.ru',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (75,2,N'www.enter.ru',N'интер',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (76,2,N'www.enter.ru',N'enter',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (77,2,N'www.enter.ru',N'энтер',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (78,2,N'www.enter.ru',N'ентер',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (79,2,N'www.enter.ru',N'утеук',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (80,2,N'www.enter.ru',N'интер',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (81,3,N'wikimart.ru',N'викимарт',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (82,3,N'wikimart.ru',N'wikimart',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (83,3,N'wikimart.ru',N'wikimart.ru',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (84,3,N'wikimart.ru',N'планшеты недорогие но хорошие',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (85,3,N'wikimart.ru',N'викимарт новосибирск',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (86,3,N'wikimart.ru',N'wikimart',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (87,3,N'wikimart.ru',N'викимарт',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (88,3,N'wikimart.ru',N'iphone 5c',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (89,3,N'wikimart.ru',N'iphone 5',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (90,3,N'wikimart.ru',N'викимаркет',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (91,4,N'www.ozon.ru',N'озон',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (92,4,N'www.ozon.ru',N'ozon',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (93,4,N'www.ozon.ru',N'ozon.ru',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (94,4,N'www.ozon.ru',N'озон интернет-магазин',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (95,4,N'www.ozon.ru',N'jpjy',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (96,4,N'www.ozon.ru',N'озон',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (97,4,N'www.ozon.ru',N'ozon',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (98,4,N'www.ozon.ru',N'jpjy',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (99,4,N'www.ozon.ru',N'щящт',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (100,4,N'www.ozon.ru',N'ozone',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (101,5,N'www.letu.ru',N'летуаль',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (102,5,N'www.letu.ru',N'летуаль интернет магазин',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (103,5,N'www.letu.ru',N'летуаль официальный сайт',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (104,5,N'www.letu.ru',N'letu',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (105,5,N'www.letu.ru',N'лету',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (106,5,N'www.letu.ru',N'летуаль',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (107,5,N'www.letu.ru',N'летуаль официальный сайт',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (108,5,N'www.letu.ru',N'colare colare bianca',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (109,5,N'www.letu.ru',N'летуаль вивьен сабо',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (110,5,N'www.letu.ru',N'clarins летуаль',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (111,6,N'www.quelle.ru',N'квелли',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (112,6,N'www.quelle.ru',N'quelle',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (113,6,N'www.quelle.ru',N'квелли интернет магазин одежды',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (114,6,N'www.quelle.ru',N'квелле',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (115,6,N'www.quelle.ru',N'интернет магазин одежды',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (116,6,N'www.quelle.ru',N'квелли',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (117,6,N'www.quelle.ru',N'quelle',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (118,6,N'www.quelle.ru',N'квелле',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (119,6,N'www.quelle.ru',N'отто',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (120,6,N'www.quelle.ru',N'квелли женская одежда',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (121,7,N'www.tehnosila.ru',N'техносила',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (122,7,N'www.tehnosila.ru',N'техносила интернет магазин',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (123,7,N'www.tehnosila.ru',N'nt[yjcbkf',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (124,7,N'www.tehnosila.ru',N'tehnosila',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (125,7,N'www.tehnosila.ru',N'техносила воронеж',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (126,7,N'www.tehnosila.ru',N'техносила',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (127,7,N'www.tehnosila.ru',N'tehnosila',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (128,7,N'www.tehnosila.ru',N'техносила смоленск',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (129,7,N'www.tehnosila.ru',N'техносила спб',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (130,7,N'www.tehnosila.ru',N'техносила воронеж',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (131,8,N'www.mvideo.ru',N'м видео',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (132,8,N'www.mvideo.ru',N'мвидео',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (133,8,N'www.mvideo.ru',N'mvideo',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (134,8,N'www.mvideo.ru',N'м-видео',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (135,8,N'www.mvideo.ru',N'vdbltj',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (136,8,N'www.mvideo.ru',N'м видео',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (137,8,N'www.mvideo.ru',N'mvideo',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (138,8,N'www.mvideo.ru',N'мвидео',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (139,8,N'www.mvideo.ru',N'м-видео',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (140,8,N'www.mvideo.ru',N'm-video',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (141,9,N'www.asos.com',N'asos',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (142,9,N'www.asos.com',N'asos marketplace',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (143,9,N'www.asos.com',N'асос',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (144,9,N'www.asos.com',N'asos uk',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (145,9,N'www.asos.com',N'asos us',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (146,9,N'www.asos.com',N'asos',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (147,9,N'www.asos.com',N'asos us',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (148,9,N'www.asos.com',N'асос',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (149,9,N'www.asos.com',N'asos curve',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (150,9,N'www.asos.com',N'asos australia',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (151,10,N'moscow.shop.megafon.ru',N'мегафон',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (152,10,N'moscow.shop.megafon.ru',N'мегафон интернет магазин',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (153,10,N'moscow.shop.megafon.ru',N'мегафон магазин',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (154,10,N'moscow.shop.megafon.ru',N'планшет мегафон',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (155,10,N'moscow.shop.megafon.ru',N'megafon',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (156,10,N'moscow.shop.megafon.ru',N'мегафон',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (157,10,N'moscow.shop.megafon.ru',N'megafon',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (158,10,N'moscow.shop.megafon.ru',N'киберпонедельник',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (159,10,N'moscow.shop.megafon.ru',N'мегафон магазин',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (160,10,N'moscow.shop.megafon.ru',N'iphone 5s',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (161,11,N'www.bgshop.ru',N'библио глобус',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (162,11,N'www.bgshop.ru',N'библио глобус книжный',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (163,11,N'www.bgshop.ru',N'библио глобус интернет магазин',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (164,11,N'www.bgshop.ru',N'книжный интернет магазин',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (165,11,N'www.bgshop.ru',N'библиоглобус',N'organic');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (166,11,N'www.bgshop.ru',N'визитницы на 60 карт',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (167,11,N'www.bgshop.ru',N'антонио гауди. artnote.',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (168,11,N'www.bgshop.ru',N'папка-портфель а4 40мм с замком серая 0.70мм &quot;proff. standart&quot;',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (169,11,N'www.bgshop.ru',N'скетчбук',N'paid');
INSERT `Keywords` (`ID`,`SiteID`,`Link`,`Keyword`,`KeywordType`) VALUES (170,12,N'www.shop.mts.ru',N'мтс интернет магазин',N'organic');
